### ISSUE TITLE
Should we archive this repo

### ISSUE THREAD

**Issue by goneall** [spdx/OLD-ntia-conformance-checker#1]
@licquia - Since this is named "OLD" - is this repo no longer in use and should we archive it?

**Comment by jspeed-meyers** [comment]
@goneall, +1 on archiving this to avoid potential confusion.

Friendly ping to @licquia

**Comment by licquia** [comment]
@goneall +1

**Comment by goneall** [comment]
Thanks @licquia - I'll archive this repo now
